import type {Metadata} from "next";

import Link from "next/link"

import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "donancy",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="dark">
        {children}
        {/* <Toaster /> */}

      </body>
    </html>
  );
}
